feat(sampling): Rename `TransmissivityMatrix`
Budapest-Quantum-Computing-Group/piquasso pull request #168
Opened 2022-03-29 10:58 UTC by Kolarovszki

`TransmissivityMatrix` got renamed to `LossyInterferometer`, since the
latter name is more descriptive regarding its usage.

2022-03-29 12:31 UTC, Tomev requested changes
Aside from the review comments I'd also like to discuss the 

test_LossyInterferometer_is_equivalent_to_Loss_and_Interferometers

test.

2022-03-29 12:31 UTC, Tomev commented on piquasso/instructions/channels.py
>          pq.Q() | pq.Interferometer(W) | pq.Loss(np.diag(D)) | pq.Interferometer(V)
I think it'd be worth noting that the _W_ and _V_ interferometers and the vector _D_ are the results of the SVD of the (possibly lossy) interferometer _A_.

2022-03-29 12:31 UTC, Tomev commented on piquasso/instructions/channels.py
>      """Applies a loss channel to the state via a transmissivity matrix.
I propose:

Applies a lossy interferometer (specified by a matrix) to the state.

The "loss channel" kind of feels like a "pure loss channel" which is not the case here.

2022-03-29 12:31 UTC, Tomev commented on piquasso/instructions/channels.py
>      The transmissivity matrix :math:`A` should have singular values in the interval
"The matrix" or "The lossy interferometer matrix".

2022-03-29 12:31 UTC, Tomev commented on piquasso/instructions/channels.py
>              When the singular values are not in the interval :math:`[0, 1]`.
Are **not** in the interval?

2022-03-29 12:31 UTC, Tomev commented on tests/backends/sampling/test_gates.py
> -def test_TransmissivityMatrix(generate_unitary_matrix):
There's a non-negligible chance that this test will fail. Consider larger losses or more samples.

2022-03-29 12:31 UTC, Tomev commented on tests/backends/sampling/test_gates.py
> -def test_TransmissivityMatrix(generate_unitary_matrix):
Maybe a totally lossy mode?

2022-03-29 12:31 UTC, Tomev commented on tests/backends/sampling/test_gates.py
>      r"""
I don't think this comment is accurate.

2022-03-29 12:31 UTC, Tomev commented on tests/backends/sampling/test_gates.py
>      r"""
Again, the description is not right.

2022-03-29 14:13 UTC, Kolarovszki commented on piquasso/instructions/channels.py
>              When the singular values are not in the interval :math:`[0, 1]`.
Yeah, this sentence describes the condition in which the exception `InvalidParameter` is raised.

2022-03-29 14:16 UTC, Kolarovszki commented on tests/backends/sampling/test_gates.py
> -def test_TransmissivityMatrix(generate_unitary_matrix):
True. Same should be done for the test above called `test_lossy_program`, right?

2022-03-29 14:28 UTC, Kolarovszki commented on tests/backends/sampling/test_gates.py
> -def test_TransmissivityMatrix(generate_unitary_matrix):
done

2022-03-29 14:28 UTC, Kolarovszki commented on piquasso/instructions/channels.py
>          pq.Q() | pq.Interferometer(W) | pq.Loss(np.diag(D)) | pq.Interferometer(V)
done

2022-03-30 06:47 UTC, Tomev approved these changes
My only issue is that the tests don't pass, but I've been told that's not the issue with the code. In the light of that - I approve. :)

2022-03-30 06:47 UTC, Tomev commented on piquasso/instructions/channels.py
>          pq.Q() | pq.Interferometer(W) | pq.Loss(np.diag(D)) | pq.Interferometer(V)
+1

2022-03-30 06:47 UTC, Tomev commented on piquasso/instructions/channels.py
>              When the singular values are not in the interval :math:`[0, 1]`.
Ah, yes, this part of the comment was skipped. I can see it now, it's good.

2022-03-30 06:47 UTC, Tomev commented on tests/backends/sampling/test_gates.py
> -def test_TransmissivityMatrix(generate_unitary_matrix):
+1

2022-03-30 19:18 UTC, merged